### ISSUE TITLE
I suggest CI travis tests

### ISSUE THREAD

**Issue by ianheggie** [shlima/health_bit#5]
Your project looks interesting, and I hope it grows to the point I can retire health_check from active development - the legacy baggage has grown.

I suggest a CI auto test that builds a rails app, includes this gem and then checks everything works.

I have added a comment " HealthBit - inspired by this gem but with a fresh start as a simpler rack only application, no travis CI tests (yet?) but looks interesting" to my health_check gem README to cross link.

**Comment by shlima** [comment]
This project uses [github actions](https://github.com/shlima/health_bit/actions). `HealthBit` is a simple rack function, which returns status code, headers and body. There is no need to test it with rails.

**Comment by ianheggie** [comment]
I didn't twig you had Ci vi github actions. If I understand you correctly, you don't health check rails then, since you don't need to test against it.
