### ISSUE TITLE
Cloning HealthBit does not clone configuration

### ISSUE THREAD

**Issue by greena13** [shlima/health_bit#8]
HealthBit version: 0.1.8

When doing the following:

```ruby
HealthBit.configure do |c|
  c.success_text = 'Custom message.'
end

CheckA = HealthBit.clone
Check B = HealthBit.clone
```

The `configure` block is ignored. To get it to work you must instead do:

```ruby
CheckA = HealthBit.clone
Check B = HealthBit.clone

CheckA.configure do |c|
  c.success_text = 'Custom message.'
end

CheckB.configure do |c|
  c.success_text = 'Custom message.'
end
```

I'd expect the former to clone the configuration from `HealthBit` so you can DRY up common configuration.

**Comment by shlima** [comment]
This is expected behaviour by design
